export var question = [
  "Touche ta langue avec ton coude et prends une photo ",
  "prends une photo avec ton voisin de gauche",
  "prends une photo avec ton voisin de droite ",
  "prends une photo avec la mariée ",
  "prends une photo avec le marié",
  "prends une photo du plus beau temoin ( boris ) ",
  "prends une photo à trois ",
  "prends une photo en buvant ",
  "prends une photo avec une belle personne",
  "prends une photo avec la personne au bout de la table",
  "prends une photo avec ton téléphone a l'envers",
  "prends une photo de toi en contre-plongée",
  "prends un bébé en photo ( boris ne compte pas meme s'il a la peau douce ) ",
  "prends une photo des mariés ensemble",
  "prends un couple en photo",
  "prends une photo  à 5 ",
  "prends une photo à 4 ",
  "prends une photo de quelqu'un assis",
  "prends une photo de quelqu'un debout",
  "prends une photo de toi assis",
  "prends une photo des mariés discretement",
  "prends une photo  d'une vielle personne ( + 30 ans )",
  "prends une photo d'une personne que tu trouves très drole ",
  "prends en photo la plus belle coupe de cheveux",
  "prends en photo quelqu'un de sportif",
  "prends une photo de toi sur la pointe des pieds ",
  "prends une photo avec le plus beau temoin ( boris ) ",
  "prends en photo une témoin",
  "prends toi en photo avec une témoin",
  "prends toi en photo à travers un verre",
  "prends quelqu'un en photo à travers un verre",
  "prends une photo très floue",
];
